env:
  APP NAME: my-app
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Show then
        env:
          GREETING: HELLO
        run: echo "SAPP_NAME $NODE_ENV $GREETING"
